apiVersion: v1
kind: Secret
metadata:
  name: syncope
  labels:
    app: {{ template "sitewhere-infra-core.name" . }}
    chart: {{ template "sitewhere-infra-core.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: c3luY29wZQ==
