apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ template "sitewhere-infra-core.relasename" . }}-syncope-environment-config
data:
 DBMS: postgresql
 DB_URL:  jdbc:postgresql://{{ include "sitewhere-infra-core.relasename" . }}-postgresql-headless:5432/syncope
 DB_USER: {{.Values.syncope.syncopeEnvironment.dbUser}}
 DB_POOL_MAX: "{{.Values.syncope.syncopeEnvironment.dbPoolMax}}"
 DB_POOL_MIN: "{{.Values.syncope.syncopeEnvironment.dbPoolMin}}"
 OPENJPA_REMOTE_COMMIT: sjvm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sitewhere-infra-core.relasename" . }}-{{.Values.syncope.syncopeConfig.name}}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: "{{ template "sitewhere-infra-core.relasename" . }}-{{.Values.syncope.syncopeConfig.name}}"
        app.kubernetes.io/name: "{{ template "sitewhere-infra-core.relasename" . }}-{{ .Values.syncope.syncopeConfig.name }}"
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "infrastructure"
        sitewhere.io/name: "syncope"
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c', 
          'until pg_isready -h {{ template "sitewhere-infra-core.relasename" . }}-postgresql-headless -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: {{.Values.syncope.syncopeConfig.name}}
        envFrom:
        - configMapRef:
           name: {{ template "sitewhere-infra-core.relasename" . }}-syncope-environment-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: syncope
              key: postgresql-password
        image: "{{.Values.syncope.syncopeConfig.repository}}/{{.Values.syncope.syncopeConfig.container}}:{{.Values.syncope.syncopeConfig.tag}}"
        ports:
        - containerPort: {{.Values.syncope.syncopeConfig.containerPort}}
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "sitewhere-infra-core.relasename" . }}-{{.Values.syncope.syncopeConfig.name}}"
spec:
  type: "{{.Values.syncope.syncopeConfig.serviceType}}"
  selector:
    name: "{{ template "sitewhere-infra-core.relasename" . }}-{{.Values.syncope.syncopeConfig.name}}"
  ports:
  - port: {{.Values.syncope.syncopeConfig.containerPort}}
    name: http-api
