# Default values for SiteWhere Database infrastructure components.
mongodb:
  podAnnotations:
    sidecar.istio.io/inject: "false"
  usePassword: false
  replicaSet:
    enabled: true
    replicas:
      secondary: 1
      arbiter: 1
  persistence:
    accessModes:
      - ReadWriteOnce
    storage: 10Gi
cassandra:
  enabled: false
  podAnnotations:
    sidecar.istio.io/inject: "false"
  persistence:
    accessMode: ReadWriteOnce
    size: 10Gi
influxdb:
  enabled: false
  podAnnotations:
    sidecar.istio.io/inject: "false"
  persistence:
    accessMode: ReadWriteOnce
    size: 10Gi
# Warp 10 Time Series Database
warp10:
  enabled: false
  podAnnotations:
    sidecar.istio.io/inject: "false"
  persistence:
    accessMode: ReadWriteOnce
    size: 10Gi
# Postgres Database
tenantsdb:
  enabled: true
  master:
    podAnnotations:
      sidecar.istio.io/inject: "false"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
  postgresqlUsername: sitewhere
  postgresqlDatabase: tenantsdb

