# SiteWhere Infrastructure
sitewhere-infra-core:
  cp-kafka:
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
      "default.replication.factor": 1
      "min.insync.replicas": 1
      "confluent.metrics.reporter.topic.partitions": 12
      "confluent.metrics.reporter.topic.replicas": 1
    brokers: 1
    external:
      enabled: false
    persistence:
      storageClass: rook-ceph-block
  cp-zookeeper:
    servers: 1
    replicaCount: 1
    service:
      type: NodePort
    persistence:
      dataDirStorageClass: rook-ceph-block
      dataLogDirStorageClass: rook-ceph-block
  postgresql:
    persistence:
      storageClass: rook-ceph-block

sitewhere-infra-database:
  mongodb:
    replicaSet:
      enabled: false
    image:
      pullPolicy: IfNotPresent
    persistence:
      storageClass: rook-ceph-block

infra:
  mongodb:
    replicaset: ""

services:
  # profile: default|minimal
  profile: minimal
  debug: false
  kafka:
    defaultTopicReplicationFactor: 1  #set default 1 for minimal
