# Use this values to install SiteWhere using rook-ceph-block storageClass
# usage: helm install --name sitewhere -f values-rook-ceph.values sitewhere/sitewhere

sitewhere-infra-core:
  kafka:
    persistence:
      storageClass: rook-ceph-block
    zookeeper:
      persistence:
        storageClass: rook-ceph-block
sitewhere-infra-database:
  mongodb:
    persistence:
      storageClass: rook-ceph-block
  cassandra:
    persistence:
      storageClass: rook-ceph-block
  influxdb:
    persistence:
      storageClass: rook-ceph-block
