  
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: "{{ template "wrap10.name" . }}"
  labels:
    app.kubernetes.io/name: "{{ template "wrap10.name" . }}"
    helm.sh/chart: "{{ template "wrap10.chart" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  {{- if .Values.config.http.enabled }}
  - name: api
    port: {{ .Values.config.http.bind_address }}
    targetPort: {{ .Values.config.http.bind_address }}
  {{- end }}
  {{- if .Values.config.studio.enabled }}
  - name: studio
    port: {{ .Values.config.studio.bind_address }}
    targetPort: {{ .Values.config.studio.bind_address }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "wrap10.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

