# Default values for SiteWhere core infrastructure components.
kafka:
  enabled: true
  replicas: 3
  persistence:
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  zookeeper:
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: standard
      accessModes:
        - ReadWriteOnce
      storage: 10Gi
consul:
  enabled: true
  Replicas: 3

