{{- if include "microservices.asset_management.enabled" . }}
{{$data := dict "Values" .Values.services.asset_management "Defaults" .Values.services }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-asset-management
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sitewhere.io/role: "microservice"
    sitewhere.io/name: "asset-management"
spec:
  replicas: {{ .Values.services.asset_management.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-asset-management
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-asset-management
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "microservice"
        sitewhere.io/name: "asset-management"
      annotations:
{{include "sitewhere.microservice.prometheus" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-asset-management
{{- include "sitewhere.microservice.image" $data | indent 10 }}
          imagePullPolicy: {{ .Values.services.image.pullPolicy }}
          ports:
            - containerPort: 9000
            - containerPort: 9001
            - containerPort: {{ .Values.services.metrics.port }}
{{- if .Values.services.debug }}
            - containerPort: 8006
            - containerPort: 1106
{{- end }}
{{include "sitewhere.microservice.envValues" . | indent 10 }}
{{include "sitewhere.microservice.resources" $data | indent 10 }}
{{include "sitewhere.microservice.probes" . | indent 10 }}
{{include "sitewhere.microservice.imagePullSecrets" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-asset-management-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.asset_management.service.type }}
  clusterIP: None
  ports:
    - port: 9000
      targetPort: {{ .Values.services.asset_management.service.grpc.api.port }}
      protocol: TCP
      name: grpc-api
    - port: 9001
      targetPort: {{ .Values.services.asset_management.service.grpc.management.port }}
      protocol: TCP
      name: grpc-management
    - port: {{ .Values.services.metrics.port }}
      targetPort: {{ .Values.services.metrics.port }}
      protocol: HTTP
      name: http-metrics
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-asset-management
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.services.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-asset-management-debug
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
      name: tcp-jdwp
    - port: 1106
      targetPort: 1106
      protocol: TCP
      name: tcp-jmx
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-asset-management
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}