{{- if include "microservices.instance_management.enabled" . }}
{{$data := dict "Values" .Values.services.instance_management "Defaults" .Values.services }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-instance-management
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sitewhere.io/role: "microservice"
    sitewhere.io/name: "instance-management"
spec:
  replicas: {{ .Values.services.instance_management.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-instance-management
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-instance-management
        app.kubernetes.io/instance: {{ .Release.Name }}
        sitewhere.io/role: "microservice"
        sitewhere.io/name: "instance-management"
    spec:
      containers:
        - name: {{ .Chart.Name }}-instance-management
{{- include "sitewhere.microservice.image" $data | indent 10 }}
          imagePullPolicy: {{ .Values.services.image.pullPolicy }}
          ports:
            - containerPort: 9001
{{- if .Values.services.debug }}
            - containerPort: 8001
            - containerPort: 1101
{{- end }}
{{include "sitewhere.microservice.envValues" . | indent 10 }}
{{include "sitewhere.microservice.resources" $data | indent 10 }}
{{include "sitewhere.microservice.probes" . | indent 10 }}
{{include "sitewhere.microservice.imagePullSecrets" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-instance-management-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.instance_management.service.type }}
  ports:
    - port: 9001
      targetPort: {{ .Values.services.instance_management.service.grpc.management.port }}
      protocol: TCP
      name: grpc-management
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-instance-management
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.services.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-instance-management-debug
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: tcp-jdwp
    - port: 1101
      targetPort: 1101
      protocol: TCP
      name: tcp-jmx
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-instance-management
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
